build: bump bl-login for new password reset flow
boklisten/bl-admin pull request #705
Opened 2023-11-02 15:16 UTC by LarsSelbekk

2023-11-02 15:47 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sikkerhetshull: kan endre hvem som helst sitt passord](https://trello.com/c/xkpYdkXG/812-sikkerhetshull-kan-endre-hvem-som-helst-sitt-passord)

2023-11-08 08:48 UTC, AdrianAndersen requested changes
Please update the "Oppdatering av passord feilet" text

2023-11-08 08:52 UTC, AdrianAndersen commented
Update the text so that it says that it might have sent an email

2023-11-15 16:14 UTC, LarsSelbekk commented
> Please update the "Oppdatering av passord feilet" text

In what way?

2023-11-16 16:35 UTC, LarsSelbekk commented
> Please update the "Oppdatering av passord feilet" text

Done

2023-11-22 11:10 UTC, AdrianAndersen approved these changes

2023-11-22 11:23 UTC, merged